name: Deploy Multi Container project
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t devopslearnerboy/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true devopslearnerboy/react-test npm test
  after_success_builds:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t devopslearnerboy/multi-client ./client
      - run: docker build -t devopslearnerboy/multi-nginx ./nginx
      - run: docker build -t devopslearnerboy/multi-server ./server
      - run: docker build -t devopslearnerboy/multi-worker ./worker
      # Log in to the docker CLI
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      # Take those images and push them to docker hub
      - run: docker push devopslearnerboy/multi-client
      - run: docker push devopslearnerboy/multi-nginx
      - run: docker push devopslearnerboy/multi-server
      - run: docker push devopslearnerboy/multi-worker
  beanstalk_deployment:
    runs-on: ubuntu-latest
    needs: [build, after_success_builds]
    steps:
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-us-west-2-064796296637
          region: us-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip